/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;

import base.MessageDao;
import domaine.*;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import metier.ListeMessage;
import metier.ListeObjects;
import org.apache.log4j.Logger;


public class FrmChat extends javax.swing.JFrame {

    private transient User friend = null;
    private transient User owner = null;
    private transient ListeObjects<Message> lstM;
    private static Logger log = Logger.getLogger(FrmChat.class.getName());
    
    /**
     * Creates new form FrmChat
     */
    public FrmChat(User friend, User owner) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.friend = friend;
        this.owner = owner;
        lblFriendLogin.setText(friend.getLogin());
        
        TimerTask task = new TimerTask(){
            @Override
            public void run() 
            {
                actualiserChat();
            }	
	};	
        Timer timer = new Timer();
	timer.scheduleAtFixedRate(task, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnvoyer = new java.awt.Button();
        lblFriendLogin = new java.awt.Label();
        lstChat = new java.awt.List();
        tfMessage = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnEnvoyer.setLabel("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        lblFriendLogin.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnvoyer, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFriendLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFriendLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstChat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
        sendMsg();
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void sendMsg (){
        try {
            MessageDao.sendMessage(owner.getId(), friend.getId(), tfMessage.getText());
            tfMessage.setText("");
            actualiserChat();
        } catch (SQLException e) {
            log.info(e);
        }
    }
    
    private void actualiserChat(){
        try {
            lstM = new ListeMessage(owner.getId(),friend.getId());
            for (int i = lstChat.getItemCount(); i < lstM.size(); i++) {
                lstChat.add(lstM.get(i).toString());
                lstChat.makeVisible(i);
            }
        } catch (SQLException e) {
            log.info(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnvoyer;
    private java.awt.Label lblFriendLogin;
    private java.awt.List lstChat;
    private java.awt.TextField tfMessage;
    // End of variables declaration//GEN-END:variables
}
