/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;

import base.MessageDao;
import domaine.User;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import metier.ListeMessage;


public class FrmChat extends javax.swing.JFrame {

    User friend = new User(-1,null);
    User owner = new User(-1,null);
    ListeMessage lstM;
    
    /**
     * Creates new form FrmChat
     */
    public FrmChat(User friend, User owner) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.friend = friend;
        this.owner = owner;
        LblFriendLogin.setText(friend.getLogin());
        
        TimerTask task = new TimerTask(){
            @Override
            public void run() 
            {
                actualiserChat();
            }	
	};	
        Timer timer = new Timer();
	timer.scheduleAtFixedRate(task, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEnvoyer = new java.awt.Button();
        LblFriendLogin = new java.awt.Label();
        LstChat = new java.awt.List();
        TfMessage = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BtnEnvoyer.setLabel("Envoyer");
        BtnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnvoyerActionPerformed(evt);
            }
        });

        LblFriendLogin.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LstChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEnvoyer, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblFriendLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFriendLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LstChat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnvoyerActionPerformed
        sendMsg();
    }//GEN-LAST:event_BtnEnvoyerActionPerformed

    private void sendMsg (){
        MessageDao.sendMessage(owner.getId(), friend.getId(), TfMessage.getText());
        TfMessage.setText("");
        actualiserChat();
    }
    
    private void actualiserChat(){
        lstM = new ListeMessage(owner.getId(),friend.getId());
        for (int i = LstChat.getItemCount(); i < lstM.size(); i++) {
            LstChat.add(lstM.get(i).toString());
            LstChat.makeVisible(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnEnvoyer;
    private java.awt.Label LblFriendLogin;
    private java.awt.List LstChat;
    private java.awt.TextField TfMessage;
    // End of variables declaration//GEN-END:variables
}
