/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;
import base.ConnexionBase;
import base.UserDao;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;


public class FrmLogin extends javax.swing.JFrame {

    private static FrmLogin uniqueInstance = null;
    private FrmMain frmMain; 
    private static Logger log = Logger.getLogger(FrmLogin.class.getName());
    
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfLogin = new java.awt.TextField();
        label1 = new java.awt.Label();
        btnConnecter = new java.awt.Button();
        tfPassword = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tfLogin.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfLoginTextValueChanged(evt);
            }
        });

        label1.setText("Connexion");

        btnConnecter.setActionCommand("Connecter");
        btnConnecter.setEnabled(false);
        btnConnecter.setLabel("Connecter");
        btnConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnecterActionPerformed(evt);
            }
        });

        tfPassword.setEchoChar('*');
        tfPassword.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfPasswordTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConnecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfLoginTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tfLoginTextValueChanged
        TfsValide();
    }//GEN-LAST:event_tfLoginTextValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!frmMain.ownerExist()) {
            ConnexionBase.close();
            System.exit(0);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnecterActionPerformed
        try{
            if (UserDao.logUser(tfLogin.getText(),tfPassword.getText())!=null) {
                frmMain.setOwner(UserDao.logUser(tfLogin.getText(),tfPassword.getText()));
                frmMain.actualiserListeAmis();
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(null,"Login ou mot de passe incorrect.","", JOptionPane.ERROR_MESSAGE); 
            }
        }catch(Exception e){
            log.info(e);
        }
            
    }//GEN-LAST:event_btnConnecterActionPerformed

    private void tfPasswordTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tfPasswordTextValueChanged
        TfsValide();
    }//GEN-LAST:event_tfPasswordTextValueChanged

    public static FrmLogin getInstance (FrmMain frmMain) {
        if (uniqueInstance == null) {uniqueInstance = new FrmLogin(); uniqueInstance.frmMain = frmMain;}
        return uniqueInstance;
    }
    
    private void TfsValide(){
        if (!tfPassword.getText().isEmpty() && !tfLogin.getText().isEmpty()) {
            btnConnecter.setEnabled(true);
        }else{
            btnConnecter.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnConnecter;
    private java.awt.Label label1;
    private java.awt.TextField tfLogin;
    private java.awt.TextField tfPassword;
    // End of variables declaration//GEN-END:variables
}
