/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;
import base.ConnexionBase;
import base.UserDao;
import javax.swing.JOptionPane;


public class FrmLogin extends javax.swing.JFrame {

    private static FrmLogin uniqueInstance = null;
    private FrmMain frmMain; 
    
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        TfLogin = new java.awt.TextField();
        label1 = new java.awt.Label();
        BtnConnecter = new java.awt.Button();
        TfPassword = new java.awt.TextField();

        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TfLogin.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                TfLoginTextValueChanged(evt);
            }
        });

        label1.setText("Connexion");

        BtnConnecter.setActionCommand("Connecter");
        BtnConnecter.setEnabled(false);
        BtnConnecter.setLabel("Connecter");
        BtnConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConnecterActionPerformed(evt);
            }
        });

        TfPassword.setEchoChar('*');
        TfPassword.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                TfPasswordTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConnecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfLoginTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_TfLoginTextValueChanged
        TfsValide();
    }//GEN-LAST:event_TfLoginTextValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (frmMain.owner.getId()==-1) {
            ConnexionBase.close();
            System.exit(0);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void BtnConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConnecterActionPerformed
        if (UserDao.logUser(TfLogin.getText(),TfPassword.getText())!=null) {
            frmMain.owner = UserDao.logUser(TfLogin.getText(),TfPassword.getText());
            frmMain.actualiserListeAmis();
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null,"Login ou mot de passe incorrect.","", JOptionPane.ERROR_MESSAGE); 
        }
            
    }//GEN-LAST:event_BtnConnecterActionPerformed

    private void TfPasswordTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_TfPasswordTextValueChanged
        TfsValide();
    }//GEN-LAST:event_TfPasswordTextValueChanged

    public static FrmLogin getInstance (FrmMain frmMain) {
        if (uniqueInstance == null) {uniqueInstance = new FrmLogin(); uniqueInstance.frmMain = frmMain;}
        return uniqueInstance;
    }
    
    private void TfsValide(){
        if (!TfPassword.getText().isEmpty() && !TfLogin.getText().isEmpty()) {
            BtnConnecter.setEnabled(true);
        }else{
            BtnConnecter.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnConnecter;
    private java.awt.TextField TfLogin;
    private java.awt.TextField TfPassword;
    private java.awt.Label label1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
