/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;
import base.ConnexionBase;
import base.UserDao;
import domaine.User;
import javax.swing.JOptionPane;
import metier.ListeUserFriends;


public class FrmMain extends javax.swing.JFrame {

    public User owner = new User(-1,null);
    public static String ADDRESS;
    public static int PORT;
    public static boolean CONNECTION_ESTABLISHED = false;
    ListeUserFriends lstF;
    /**
     * Creates new form FrmFriends
     */
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenue = new java.awt.Label();
        lblAmis = new java.awt.Label();
        LstAmis = new java.awt.List();
        BtnSuprimerAmi = new java.awt.Button();
        BtnChatterAmi = new java.awt.Button();
        BtnDeconnecter = new java.awt.Button();
        BtnAjoutAmi = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Java");
        setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 12)); // NOI18N
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblBienvenue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBienvenue.setText("Bienvenue ");

        lblAmis.setText("Amis :");

        LstAmis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LstAmisItemStateChanged(evt);
            }
        });

        BtnSuprimerAmi.setEnabled(false);
        BtnSuprimerAmi.setLabel("Suprimer");
        BtnSuprimerAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuprimerAmiActionPerformed(evt);
            }
        });

        BtnChatterAmi.setEnabled(false);
        BtnChatterAmi.setLabel("Chatter avec");
        BtnChatterAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChatterAmiActionPerformed(evt);
            }
        });

        BtnDeconnecter.setEnabled(false);
        BtnDeconnecter.setLabel("Se déconnecter");
        BtnDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeconnecterActionPerformed(evt);
            }
        });

        BtnAjoutAmi.setLabel("Ajouter un ami");
        BtnAjoutAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutAmiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LstAmis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDeconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAjoutAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblBienvenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSuprimerAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnChatterAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnChatterAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LstAmis, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSuprimerAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnDeconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAjoutAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setServer(String address, int port){
        ADDRESS = address;
        PORT = port;
    }
    
    public static void setConnectionStat(boolean conEstab){
        CONNECTION_ESTABLISHED = conEstab;
    }
    
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if (owner.getId()==-1 && CONNECTION_ESTABLISHED) {
            FrmLogin.getInstance(this).setVisible(true);
        }else if(CONNECTION_ESTABLISHED == false){
            FrmLoading.getInstance(this).setVisible(true);
            FrmLoading.getInstance(this).tryConnection(0);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ConnexionBase.close();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void LstAmisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LstAmisItemStateChanged
        if (LstAmis.getSelectedIndex()!=-1) {
            BtnChatterAmi.setEnabled(true);
            BtnSuprimerAmi.setEnabled(true);
            
        }else{
            BtnChatterAmi.setEnabled(false);
            BtnSuprimerAmi.setEnabled(false);
        }
    }//GEN-LAST:event_LstAmisItemStateChanged

    private void BtnChatterAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChatterAmiActionPerformed
        lstF.setPos(LstAmis.getSelectedIndex());
        new FrmChat(lstF.getCourant(),owner).setVisible(true);
    }//GEN-LAST:event_BtnChatterAmiActionPerformed

    private void BtnSuprimerAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuprimerAmiActionPerformed
        lstF.setPos(LstAmis.getSelectedIndex());
        UserDao.deleteFriend(owner.getId(), lstF.getCourant().getId());
        actualiserListeAmis();
    }//GEN-LAST:event_BtnSuprimerAmiActionPerformed

    private void BtnDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeconnecterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeconnecterActionPerformed

    private void BtnAjoutAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutAmiActionPerformed
        String ami = JOptionPane.showInputDialog("Chercher un ami :");
        if (ami != "") {
            
        }
    }//GEN-LAST:event_BtnAjoutAmiActionPerformed

    public void actualiserListeAmis(){
        LstAmis.removeAll();
        lblBienvenue.setText("Bienvenue " + owner.getLogin());
        lstF = new ListeUserFriends(owner.getId());
        for (int i = 0; i < lstF.size(); i++) {
            LstAmis.add(lstF.get(i).getLogin());
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnAjoutAmi;
    private java.awt.Button BtnChatterAmi;
    private java.awt.Button BtnDeconnecter;
    private java.awt.Button BtnSuprimerAmi;
    private java.awt.List LstAmis;
    private java.awt.Label lblAmis;
    private java.awt.Label lblBienvenue;
    // End of variables declaration//GEN-END:variables
}
