/**
 *
 * @author Rodriguez Thomas
 * @version 1.2
 */
package presentation;
import base.ConnexionBase;
import base.UserDao;
import domaine.User;
import java.sql.SQLException;
import metier.*;
import org.apache.log4j.Logger;


public class FrmMain extends javax.swing.JFrame {

    private transient User owner = null;
    private transient ListeObjects<User> lstF;
    private static Logger log = Logger.getLogger(FrmMain.class.getName());
    /**
     * Creates new form FrmFriends
     */
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenue = new java.awt.Label();
        lblAmis = new java.awt.Label();
        lstAmis = new java.awt.List();
        btnSuprimerAmi = new java.awt.Button();
        btnChatterAmi = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Java");
        setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 12)); // NOI18N
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblBienvenue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBienvenue.setText("Bienvenue ");

        lblAmis.setText("Amis :");

        lstAmis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstAmisItemStateChanged(evt);
            }
        });

        btnSuprimerAmi.setEnabled(false);
        btnSuprimerAmi.setLabel("Suprimer");
        btnSuprimerAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuprimerAmiActionPerformed(evt);
            }
        });

        btnChatterAmi.setEnabled(false);
        btnChatterAmi.setLabel("Chatter avec");
        btnChatterAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatterAmiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lstAmis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblBienvenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSuprimerAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(btnChatterAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChatterAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstAmis, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuprimerAmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if (owner==null) {
            FrmLogin.getInstance(this).setVisible(true);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ConnexionBase.close();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void lstAmisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstAmisItemStateChanged
        if (lstAmis.getSelectedIndex()!=-1) {
            btnChatterAmi.setEnabled(true);
            btnSuprimerAmi.setEnabled(true);
            
        }else{
            btnChatterAmi.setEnabled(false);
            btnSuprimerAmi.setEnabled(false);
        }
    }//GEN-LAST:event_lstAmisItemStateChanged

    private void btnChatterAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatterAmiActionPerformed
        lstF.setPos(lstAmis.getSelectedIndex());
        new FrmChat(lstF.getCourant(),owner).setVisible(true);
    }//GEN-LAST:event_btnChatterAmiActionPerformed

    private void btnSuprimerAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuprimerAmiActionPerformed
        try {
            lstF.setPos(lstAmis.getSelectedIndex());
            UserDao.deleteFriend(owner.getId(), lstF.getCourant().getId());
            actualiserListeAmis();
        } catch (SQLException e) {
            log.error(e);
        }
    }//GEN-LAST:event_btnSuprimerAmiActionPerformed

    public void actualiserListeAmis(){
        try {
            lstAmis.removeAll();
            lblBienvenue.setText("Bienvenue " + owner.getLogin());
            lstF = new ListeUserFriends(owner.getId());
            for (int i = 0; i < lstF.size(); i++) {
                lstAmis.add(lstF.get(i).getLogin());
            }
        } catch (SQLException e) {
            log.error(e);
        }
    }
    
    public void setOwner(User owner){
        this.owner = owner;
    }
    
    public boolean ownerExist(){
        if(this.owner!=null){
            return true;
        }
        return false;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnChatterAmi;
    private java.awt.Button btnSuprimerAmi;
    private java.awt.Label lblAmis;
    private java.awt.Label lblBienvenue;
    private java.awt.List lstAmis;
    // End of variables declaration//GEN-END:variables
}
